name: Evolution
version: ${version}
description: Plugin exclusivo do servidor Evolution
website: 'https://github.com/FocaEnterprises'
authors: [ GiverPlay ]

main: me.giverplay.evolution.Evolution
api-version: 1.17
load: POSTWORLD

softdepend:
  - Vault
  - Essentials
  - LuckPerms

commands:
  rankup:
    description: 'Sobe para o proximo rank'
    aliases: [up, upar, nextrank]
  kit:
    description: 'Abre o menu dos kits'
    aliases: [kits]
  trash:
    description: 'Abre a lixeira'
    aliases: [lixo, lixeira]
  tpa:
    description: 'Solicita teleporte para outro jogador'
    aliases: [requesttp, teleportrequest, pedirtp]
  tpaccept:
    description: 'Aceita um pedido de teleporte'
    aliases: [tpaceitar, tpacc]
