name: Evolution
version: ${version}
description: Plugin exclusivo do servidor Evolution
website: 'https://github.com/FocaEnterprises'
authors: [ GiverPlay ]

main: me.giverplay.evolution.Evolution
api-version: 1.18
load: POSTWORLD

softdepend:
  - Vault
  - Essentials
  - LuckPerms

commands:
  rankup:
    description: 'Go to the next rank'
    aliases: [up, upar, nextrank]
  kit:
    description: 'Open kit categories menu'
    aliases: [kits]
