name: Build

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0

    - name: Setup JDK
      uses: actions/setup-java@v2.5.0
      with:
        java-version: 17
        distribution: corretto

    - name: Grant execute permission
      run: "chmod +x ./gradlew"

    - name: Build with Gradle
      run: "./gradlew build"
    
    - name: Copy compiled jars into output folder
      run: mkdir output && cp build/libs/*.jar output
    
    - name: Upload compiled jars
      uses: actions/upload-artifact@v2.3.1
      with:
        name: Artifacts
        path: output
