name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0

    - name: Setup JDK
      uses: actions/setup-java@v2.5.0
      with:
        java-version: 17
        distribution: adopt
      
    - name: Download PaperMC
      continue-on-error: true
      run: |
       mkdir libs
       mkdir server
       cd server
       curl -s -o paper.jar https://papermc.io/api/v2/projects/paper/versions/1.18.2/builds/250/downloads/paper-1.18.2-250.jar
       java -Xmx500M -jar paper.jar
       mv ./versions/1.18.2/paper-1.18.2.jar ../libs
       cd ../
    
    - name: "Download RedProtect"
      run: |
       wget RedProtect-7.7.3-b410.jar https://cdn.discordapp.com/attachments/796091203082649640/953111565215883284/RedProtect-7.7.3-b410.jar
       mv RedProtect-7.7.3-b410.jar libs/
       
    - name: Grant execute permission
      run: "chmod +x ./gradlew"

    - name: Build with Gradle
      run: "./gradlew build"

    - name: Copy compiled jars into output folder
      run: mkdir output && cp build/libs/*.jar output

    - name: Upload compiled jars
      uses: actions/upload-artifact@v2.3.1
      with:
        name: Artifacts
        path: output
